name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'Path to directory containing terraform files. Default is current working directory'
    required: true
    default: '$GITHUB_WORKSPACE'
  workspace:
    description: 'terraform workspace'
    required: true
    default: 'default'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.workspace }}
