name: 'Terraform Deploy'
description: 'Deploy terraform with custom workspace'
inputs:
  path:
    description: 'Path to directory containing terraform files. Default is current working directory'
    required: true
    default: ''
  workspace:
    description: 'terraform workspace'
    required: true
    default: 'default'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.workspace }}
